-module(graphql_introspection_test).
-include_lib("eunit/include/eunit.hrl").
-include("types.hrl").

query() -> <<"
  query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                }
              }
            }
          }
        }
      }
    }
  }
">>.

expect() -> #{data => [{<<"__schema">>,
  [{<<"directives">>,[]},
    {<<"types">>,
      [[{<<"possibleTypes">>,[]},
        {<<"enumValues">>,null},
        {<<"interfaces">>,[]},
        {<<"inputFields">>,null},
        {<<"fields">>,
          [[{<<"deprecationReason">>,null},
            {<<"isDeprecated">>,<<"false">>},
            {<<"type">>,
              [{<<"ofType">>,null},
                {<<"name">>,<<"String">>},
                {<<"kind">>,<<"SCALAR">>}]},
            {<<"args">>,[]},
            {<<"description">>,null},
            {<<"name">>,<<"name">>}],
            [{<<"deprecationReason">>,null},
              {<<"isDeprecated">>,<<"false">>},
              {<<"type">>,
                [{<<"ofType">>,null},
                  {<<"name">>,<<"String">>},
                  {<<"kind">>,<<"SCALAR">>}]},
              {<<"args">>,[]},
              {<<"description">>,<<"Name of current type">>},
              {<<"name">>,<<"__typename">>}]]},
        {<<"description">>,<<"Directive Introspection">>},
        {<<"name">>,<<"__Directive">>},
        {<<"kind">>,<<"OBJECT">>}],
        [{<<"possibleTypes">>,[]},
          {<<"enumValues">>,null},
          {<<"interfaces">>,[]},
          {<<"inputFields">>,null},
          {<<"fields">>,
            [[{<<"deprecationReason">>,null},
              {<<"isDeprecated">>,<<"false">>},
              {<<"type">>,
                [{<<"ofType">>,null},
                  {<<"name">>,<<"String">>},
                  {<<"kind">>,<<"SCALAR">>}]},
              {<<"args">>,[]},
              {<<"description">>,null},
              {<<"name">>,<<"name">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"Boolean">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"isDeprecated">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"description">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"deprecationReason">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,<<"Name of current type">>},
                {<<"name">>,<<"__typename">>}]]},
          {<<"description">>,<<"Enumerate value">>},
          {<<"name">>,<<"EnumValue">>},
          {<<"kind">>,<<"OBJECT">>}],
        [{<<"possibleTypes">>,[]},
          {<<"enumValues">>,null},
          {<<"interfaces">>,[]},
          {<<"inputFields">>,null},
          {<<"fields">>,
            [[{<<"deprecationReason">>,null},
              {<<"isDeprecated">>,<<"false">>},
              {<<"type">>,
                [{<<"ofType">>,null},
                  {<<"name">>,<<"__Type">>},
                  {<<"kind">>,<<"OBJECT">>}]},
              {<<"args">>,[]},
              {<<"description">>,null},
              {<<"name">>,<<"type">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"name">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"description">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"Int">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"defaultValue">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,<<"Name of current type">>},
                {<<"name">>,<<"__typename">>}]]},
          {<<"description">>,<<"InputValue Introspection">>},
          {<<"name">>,<<"__InputValue">>},
          {<<"kind">>,<<"OBJECT">>}],
        [{<<"possibleTypes">>,[]},
          {<<"enumValues">>,null},
          {<<"interfaces">>,[]},
          {<<"inputFields">>,null},
          {<<"fields">>,
            [[{<<"deprecationReason">>,null},
              {<<"isDeprecated">>,<<"false">>},
              {<<"type">>,
                [{<<"ofType">>,null},
                  {<<"name">>,<<"__Type">>},
                  {<<"kind">>,<<"OBJECT">>}]},
              {<<"args">>,[]},
              {<<"description">>,null},
              {<<"name">>,<<"type">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"name">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"isDeprecated">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"description">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"deprecationReason">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,
                    [{<<"ofType">>,null},
                      {<<"name">>,<<"__InputValue">>},
                      {<<"kind">>,<<"OBJECT">>}]},
                    {<<"name">>,null},
                    {<<"kind">>,<<"LIST">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"args">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,<<"Name of current type">>},
                {<<"name">>,<<"__typename">>}]]},
          {<<"description">>,<<"Field Introspection">>},
          {<<"name">>,<<"__Field">>},
          {<<"kind">>,<<"OBJECT">>}],
        [{<<"possibleTypes">>,[]},
          {<<"enumValues">>,null},
          {<<"interfaces">>,[]},
          {<<"inputFields">>,null},
          {<<"fields">>,
            [[{<<"deprecationReason">>,null},
              {<<"isDeprecated">>,<<"false">>},
              {<<"type">>,
                [{<<"ofType">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"Int">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                  {<<"name">>,null},
                  {<<"kind">>,<<"LIST">>}]},
              {<<"args">>,[]},
              {<<"description">>,null},
              {<<"name">>,<<"possibleTypes">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"__Type">>},
                    {<<"kind">>,<<"OBJECT">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"ofType">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"name">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"kind">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,
                    [{<<"ofType">>,null},
                      {<<"name">>,<<"Int">>},
                      {<<"kind">>,<<"SCALAR">>}]},
                    {<<"name">>,null},
                    {<<"kind">>,<<"LIST">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"interfaces">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,
                    [{<<"ofType">>,null},
                      {<<"name">>,<<"Int">>},
                      {<<"kind">>,<<"SCALAR">>}]},
                    {<<"name">>,null},
                    {<<"kind">>,<<"LIST">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"inputFields">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,
                    [{<<"ofType">>,null},
                      {<<"name">>,<<"__Field">>},
                      {<<"kind">>,<<"OBJECT">>}]},
                    {<<"name">>,null},
                    {<<"kind">>,<<"LIST">>}]},
                {<<"args">>,
                  [[{<<"defaultValue">>,null},
                    {<<"type">>,
                      [{<<"ofType">>,null},
                        {<<"name">>,<<"Boolean">>},
                        {<<"kind">>,<<"SCALAR">>}]},
                    {<<"description">>,null},
                    {<<"name">>,<<"includeDeprecated">>}]]},
                {<<"description">>,null},
                {<<"name">>,<<"fields">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,
                    [{<<"ofType">>,null},
                      {<<"name">>,<<"EnumValue">>},
                      {<<"kind">>,<<"OBJECT">>}]},
                    {<<"name">>,null},
                    {<<"kind">>,<<"LIST">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"enumValues">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"description">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,<<"Name of current type">>},
                {<<"name">>,<<"__typename">>}]]},
          {<<"description">>,<<"Type Introspection">>},
          {<<"name">>,<<"__Type">>},
          {<<"kind">>,<<"OBJECT">>}],
        [{<<"possibleTypes">>,[]},
          {<<"enumValues">>,null},
          {<<"interfaces">>,[]},
          {<<"inputFields">>,null},
          {<<"fields">>,
            [[{<<"deprecationReason">>,null},
              {<<"isDeprecated">>,<<"false">>},
              {<<"type">>,
                [{<<"ofType">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"__Type">>},
                    {<<"kind">>,<<"OBJECT">>}]},
                  {<<"name">>,null},
                  {<<"kind">>,<<"LIST">>}]},
              {<<"args">>,[]},
              {<<"description">>,null},
              {<<"name">>,<<"types">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"__Type">>},
                    {<<"kind">>,<<"OBJECT">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"subscriptionType">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"__Type">>},
                    {<<"kind">>,<<"OBJECT">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"queryType">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"__Type">>},
                    {<<"kind">>,<<"OBJECT">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"mutationType">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,
                    [{<<"ofType">>,null},
                      {<<"name">>,<<"__Directive">>},
                      {<<"kind">>,<<"OBJECT">>}]},
                    {<<"name">>,null},
                    {<<"kind">>,<<"LIST">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"directives">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,<<"Name of current type">>},
                {<<"name">>,<<"__typename">>}]]},
          {<<"description">>,<<"Schema Introspection">>},
          {<<"name">>,<<"__Schema">>},
          {<<"kind">>,<<"OBJECT">>}],
        [{<<"possibleTypes">>,[]},
          {<<"enumValues">>,
            [[{<<"deprecationReason">>,null},
              {<<"isDeprecated">>,false},
              {<<"description">>,
                <<"This is 1 represent as text">>},
              {<<"name">>,<<"ONE">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,false},
                {<<"description">>,
                  <<"This is 2 represent as text">>},
                {<<"name">>,<<"TWO">>}]]},
          {<<"interfaces">>,[]},
          {<<"inputFields">>,null},
          {<<"fields">>,[]},
          {<<"description">>,<<"Test description">>},
          {<<"name">>,<<"Test">>},
          {<<"kind">>,<<"ENUM">>}],
        [{<<"possibleTypes">>,[]},
          {<<"enumValues">>,null},
          {<<"interfaces">>,[]},
          {<<"inputFields">>,null},
          {<<"fields">>,[]},
          {<<"description">>,
            <<"The `Float` scalar type represents signed double-precision fractional values as specified by [IEEE 754](http://en.wikipedia.org/wiki/IEEE_floating_point).">>},
          {<<"name">>,<<"Float">>},
          {<<"kind">>,<<"SCALAR">>}],
        [{<<"possibleTypes">>,[]},
          {<<"enumValues">>,null},
          {<<"interfaces">>,[]},
          {<<"inputFields">>,null},
          {<<"fields">>,[]},
          {<<"description">>,
            <<"The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^53 - 1) and 2^53 - 1 since represented in JSON as double-precision floating point numbers specified by [IEEE 754](http://en.wikipedia.org/wiki/IEEE_floating_point).">>},
          {<<"name">>,<<"Int">>},
          {<<"kind">>,<<"SCALAR">>}],
        [{<<"possibleTypes">>,[]},
          {<<"enumValues">>,null},
          {<<"interfaces">>,[]},
          {<<"inputFields">>,null},
          {<<"fields">>,[]},
          {<<"description">>,
            <<"The `Boolean` scalar type represents `true` or `false`.">>},
          {<<"name">>,<<"Boolean">>},
          {<<"kind">>,<<"SCALAR">>}],
        [{<<"possibleTypes">>,[]},
          {<<"enumValues">>,null},
          {<<"interfaces">>,[]},
          {<<"inputFields">>,null},
          {<<"fields">>,
            [[{<<"deprecationReason">>,null},
              {<<"isDeprecated">>,<<"false">>},
              {<<"type">>,
                [{<<"ofType">>,null},
                  {<<"name">>,<<"Boolean">>},
                  {<<"kind">>,<<"SCALAR">>}]},
              {<<"args">>,[]},
              {<<"description">>,null},
              {<<"name">>,<<"boolean">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,<<"Name of current type">>},
                {<<"name">>,<<"__typename">>}]]},
          {<<"description">>,
            <<"Test Object introspection in list">>},
          {<<"name">>,<<"CustomObject">>},
          {<<"kind">>,<<"OBJECT">>}],
        [{<<"possibleTypes">>,[]},
          {<<"enumValues">>,null},
          {<<"interfaces">>,[]},
          {<<"inputFields">>,null},
          {<<"fields">>,[]},
          {<<"description">>,
            <<"The `String` scalar type represents textual data, represented as UTF-8character sequences. The String type is most often used by GraphQL torepresent free-form human-readable text.">>},
          {<<"name">>,<<"String">>},
          {<<"kind">>,<<"SCALAR">>}],
        [{<<"possibleTypes">>,[]},
          {<<"enumValues">>,null},
          {<<"interfaces">>,[]},
          {<<"inputFields">>,null},
          {<<"fields">>,
            [[{<<"deprecationReason">>,null},
              {<<"isDeprecated">>,<<"false">>},
              {<<"type">>,
                [{<<"ofType">>,null},
                  {<<"name">>,<<"String">>},
                  {<<"kind">>,<<"SCALAR">>}]},
              {<<"args">>,[]},
              {<<"description">>,null},
              {<<"name">>,<<"string">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,
                    [{<<"ofType">>,null},
                      {<<"name">>,<<"CustomObject">>},
                      {<<"kind">>,<<"OBJECT">>}]},
                    {<<"name">>,null},
                    {<<"kind">>,<<"LIST">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"object_list">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,
                    [{<<"ofType">>,null},
                      {<<"name">>,<<"Int">>},
                      {<<"kind">>,<<"SCALAR">>}]},
                    {<<"name">>,null},
                    {<<"kind">>,<<"NON_NULL">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"non_null">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"Int">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"integer">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"Float">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"float">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"Int">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,
                  [[{<<"defaultValue">>,null},
                    {<<"type">>,
                      [{<<"ofType">>,null},
                        {<<"name">>,<<"Test">>},
                        {<<"kind">>,<<"ENUM">>}]},
                    {<<"description">>,null},
                    {<<"name">>,<<"int">>}]]},
                {<<"description">>,null},
                {<<"name">>,<<"enums_args">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"Boolean">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"boolean">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"String">>},
                    {<<"kind">>,<<"SCALAR">>}]},
                {<<"args">>,[]},
                {<<"description">>,<<"Name of current type">>},
                {<<"name">>,<<"__typename">>}],
              [{<<"deprecationReason">>,null},
                {<<"isDeprecated">>,<<"false">>},
                {<<"type">>,
                  [{<<"ofType">>,null},
                    {<<"name">>,<<"__Schema">>},
                    {<<"kind">>,<<"OBJECT">>}]},
                {<<"args">>,[]},
                {<<"description">>,null},
                {<<"name">>,<<"__schema">>}]]},
          {<<"description">>,<<"Test Query">>},
          {<<"name">>,<<"QueryRoot">>},
          {<<"kind">>,<<"OBJECT">>}]]},
    {<<"subscriptionType">>,null},
    {<<"mutationType">>,null},
    {<<"queryType">>,[{<<"name">>,<<"QueryRoot">>}]}]}],
  errors => []}.

schema() ->
  graphql_type_schema:new(#{
    query => fun queryRoot/0
  }).

queryRoot() -> graphql:objectType(<<"QueryRoot">>, <<"Test Query">>, #{
  <<"boolean">> => #{type => ?BOOLEAN},
  <<"string">> => #{type => ?STRING},
  <<"integer">> => #{type => ?INT},
  <<"float">> => #{type => ?FLOAT},
  <<"non_null">> => #{type => ?NON_NULL(?INT)},
  <<"object_list">> => #{type => ?LIST(fun object/0)},
  <<"enums_args">> => #{
    type => ?INT,
    args => #{
      <<"int">> => #{ type => fun enum_two/0}
    }
  }
}).

object() -> graphql:objectType(<<"CustomObject">>, <<"Test Object introspection in list">>, #{
  <<"boolean">> => #{type => ?BOOLEAN}
}).

enum_two() ->
  ?ENUM(<<"Test">>, <<"Test description">>, [
    ?ENUM_VAL(1, <<"ONE">>, <<"This is 1 represent as text">>),
    ?ENUM_VAL(1, <<"TWO">>, <<"This is 2 represent as text">>)
  ]).

introspection_test()->
  ?assertEqual(
    expect(),
    graphql:execute(schema(), query(), #{})
  ).
